### ISSUE TITLE
Send requests / responses to laravel telescope?

### ISSUE THREAD

**Issue by rrolla** [Sammyjo20/saloon-laravel#21]
Hi, first thanks for the nice package, but as always it's still room to improve it.

Laravel telescope has a really nice feature **[HTTP Client](https://laravel.com/docs/9.x/telescope#http-client-watcher)** watcher records outgoing [HTTP client requests](https://laravel.com/docs/9.x/http-client) made by your application. 

![telescope](https://user-images.githubusercontent.com/3932546/179228284-d77f1923-a51c-468e-a6ad-9480d72fcfe0.jpg)

Is it plan to send requests / responses to laravel telescope?

**Comment by Sammyjo20** [comment]
Hi @rrolla!

Oooh, I wasn't aware of this but its something that can definitely be done. I will add it to my list.

**Comment by Sammyjo20** [comment]
Hey @rrolla,

I've been having a play with Telescope tonight, and thanks for your code. It gave me a really good spring-board for how this would work. Good news, it's working really well. I even got it adding a couple of tags too which is cool, so you know where the request came from. 

<img width="1239" alt="Screen Shot 2022-07-22 at 00 00 47" src="https://user-images.githubusercontent.com/29132017/180329044-350b2e7d-5f8c-4ac3-b962-58193aa16777.png">

This is the code that powers it:

```php
public function boot(SaloonRequest $request): void
{
    $this->addResponseInterceptor(function (SaloonRequest $request, SaloonResponse $response) {
        $telescope = app()->make(Telescope::class);

        $responseIsJson = Str::of($response->header('Content-Type'))->lower()->contains('application/json');

        $url = $request->getFullRequestUrl();
        $glue = str_contains($url, '?') ? '&' : '?';
        $query = http_build_query($request->getQuery());

        $fullUrl = $url . $glue . $query;

        $telescope->recordClientRequest(
            IncomingEntry::make([
                'method' => $request->getMethod(),
                'uri' => $fullUrl,
                'headers' => $request->getHeaders(),
                'payload' => $request->getData(),
                'response_status' => $response->status(),
                'response_headers' => $response->headers(),
                'response' => $responseIsJson ? $response->json() : $response->body(),
                'saloon_request' => get_class($request),
                'saloon_connector' => get_class($request->getConnector()),
            ])
        );

        return $response;
    });
}
```

What I'm thinking of doing is actually introduce two events that get thrown by Saloon when using the package called `SentSaloonRequest` and `RecievedSaloonResponse`, and then this telescope logic could be all written inside of a listener?

That way people using Telescope can choose to enable this functionality. Or would you prefer it was enabled by default?

**Comment by rrolla** [comment]
Hey, @Sammyjo20 glad that code helps you. I think yes for this package better introduce two new events and enable them by default, but with the possibility to disable them.

**Comment by Sammyjo20** [comment]
Hey @rrolla I've implemented this in #24 check it out and let me know if you need anything else!

**Comment by juse-less** [comment]
@Sammyjo20 Thanks for looking into this!
This is one of the obstacles I found in our situation, when migrating from Laravel's own HTTP Client.
I intended to post this a while ago as well, but forgot about it.

Since we're dealing with Client Requests, you could possibly check if it's enabled, using the value from the [config](https://github.com/laravel/telescope/blob/e4c8be88b886d615423c7ddef266be37b7f80c02/config/telescope.php#L125).

Should be something along the lines of
```php
$enabled = config('telescope.watchers.' . ClientRequestWatcher::class, false);
```

Telescope itself registers the watchers, only if they are enabled, [here](https://github.com/laravel/telescope/blob/e4c8be88b886d615423c7ddef266be37b7f80c02/src/RegistersWatchers.php#L31).

Another thing to keep in mind: Telescope's own [ClientRequestWatcher](https://github.com/laravel/telescope/blob/4.x/src/Watchers/ClientRequestWatcher.php) masks values according to your specified properties in Telescope (ideally, sensitive information like passwords (by default)).

If you could instead use Laravel's [builtin Events, that Telescope listens on](https://github.com/laravel/telescope/blob/e4c8be88b886d615423c7ddef266be37b7f80c02/src/Watchers/ClientRequestWatcher.php#L25-L26), all of this would happen automagically without the need for an interceptor, or so.
The downside, of course, being that it won't add which SaloonRequest was sent, or the SaloonConnector used.
But I guess, for that, you could possibly look into register some context callback, and Telescope will add that context for you.
I recall seeing that somewhere and can quickly look it up, if it's of interest.

**Comment by Sammyjo20** [comment]
Yes I would be interested in that! I looked at the watcher code, but not in depth admittedly. I didn’t think I could use it to capture HTTP events.

**Comment by Sammyjo20** [comment]
Just looked at the docs, I could definitely make a custom watcher.

**Comment by juse-less** [comment]
What I had in mind was more towards registering a callback, to add context/content to the IncomingEntry.
[This looks like the best option](https://github.com/laravel/telescope/blob/e4c8be88b886d615423c7ddef266be37b7f80c02/src/Telescope.php#L610-L615), as it's also _before_ it's saved to database (which is another callback).

However, I'm not entirely sure how to handle it correctly, when checking if it's an IncomingEntry we care for.

So, in that case, you're probably more on the right track with a custom watcher, than registering the callback I suggested.
I think you should be able to extend the ClientRequestWatcher at large, just register different events (the ones you've added), and then just copy the current `record*()` methods (for the parameter masking etc), and just add the context you want to add to it.

It does, however, look like you'll still need to somehow inject your watcher in the Telescope config.
So, maybe, to also not override if users has added your watcher explicitly, is to first check the existence of your watcher, or, add it with the same enablement as Telescopes ClientRequestWatcher (by default).
Not sure if I overcomplicate things.
```php
if (! config('telescope.watchers.' . SaloonRequestWatcher::class)) {
    // Update the default value from true, if needed.
    $enabled = config('telescope.watchers.' . ClientRequestWatcher, true);

    config(['telescope.watchers.' . SaloonRequestWatcher::class => $enabled]);
}

**Comment by Sammyjo20** [comment]
This will be coming with the Laravel HTTP client sender in v2
