### ISSUE TITLE
Dependency injection improvements

### ISSUE THREAD

**Issue by rrolla** [Sammyjo20/saloon-laravel#22]
Is it possible in saloon-laravel override `bootConnector` method so its resolve dependency from laravel service container?

Problem is when writing tests cannot manage to mock it because of this line: https://github.com/Sammyjo20/Saloon/blob/v1/src/Http/SaloonRequest.php#L110
```php
$this->setConnector(new $this->connector);
```

should be easy fix (not tested)
```php
$this->setConnector(resolve($this->connector::class));
```

I did a hacky workaround by overriding `getConnector()` so I can dependency injection my FetchifyConnector to FetchifyUKPostcodeLookupRequest https://github.com/Sammyjo20/Saloon/blob/v1/src/Http/SaloonRequest.php#L120

```php
<?php

declare(strict_types=1);

namespace App\Http\Saloon\Requests\Fetchify;

use App\Http\Saloon\Connectors\Fetchify\FetchifyConnector;
use App\Http\Saloon\Responses\Fetchify\FetchifyUKPostcodeLookupResponse;
use App\Libraries\Helpers\LaravelGlobals;
use Sammyjo20\Saloon\Constants\Saloon;
use Sammyjo20\Saloon\Http\SaloonRequest;
use Sammyjo20\Saloon\Http\SaloonConnector;

class FetchifyUKPostcodeLookupRequest extends SaloonRequest
{
    /**
     * Define the method that the request will use.
     *
     * @var string|null
     */
    protected ?string $method = Saloon::GET;

    /**
     * Define a custom response that the request will return.
     *
     * @var string|null
     */
    protected ?string $response = FetchifyUKPostcodeLookupResponse::class;
    private string $postcode;

    public function __construct(
        private readonly FetchifyConnector              $fetchifyConnector,
        private readonly LaravelGlobals                 $laravelGlobals,
    ) {

    }

    /**
     * Need to set like this to get it working with dependency injection
     *
     * @return SaloonConnector
     */
    public function getConnector(): SaloonConnector
    {
        return $this->fetchifyConnector;
    }

    /**
     * @link https://fetchify.com/docs/json-api/uk-postcode-lookup.html#full-address-rapidaddress
     * @return array
     */
    public function defaultQuery(): array
    {
        return [
            'key' => $this->laravelGlobals->config('services.fetchify.key'),
            'include_geocode' => false,
        ];
    }
}

```

```php
<?php

declare(strict_types=1);

namespace App\Http\Saloon\Connectors\Fetchify;

use App\Libraries\Helpers\LaravelGlobals;
use Sammyjo20\Saloon\Http\SaloonConnector;
use Sammyjo20\Saloon\Traits\Plugins\AcceptsJson;

class FetchifyConnector extends SaloonConnector
{
    use AcceptsJson;

    public function __construct(private LaravelGlobals $laravelGlobals)
    {
    }

    /**
     * Define the base url of the api.
     * @link https://fetchify.com/docs/json-api/uk-postcode-lookup.html#full-address-rapidaddress
     * @return string
     */
    public function defineBaseUrl(): string
    {
        return $this->laravelGlobals->config('services.fetchify.endpoint');
    }
}
```

Hope you got the point, cheers.

**Comment by Sammyjo20** [comment]
Hey, yeah this should be relatively easy to manage. I already use a Laravel detector in the LaravelManager, but it could be definitely overwritten. In V2, you'll be able to overwrite the connector by using Saloon's own middleware, where you can intercept both the request and the response, as well as Guzzle's middleware.

I imagine this would probably mean I could just overwrite the bootConnector method which will resolve one from the Laravel container.

So what are you doing in the swapped connector, are you running a mock client from within there or is it just to have a different endpoint when testing?

**Comment by Sammyjo20** [comment]
Hey @juse-less, I thought I'd mention you on this issue. Would this proposed solution resolve your issue too? I know that you mentioned you couldn't use dependency injection for the connector.

**Comment by Sammyjo20** [comment]
Alternatively guys, I could create a new method called "resolveConnector" which can be extended and just returns the ability to new-up a class?

**Comment by juse-less** [comment]
Your alternative solution is pretty much what I thought would be the easiest path ([point 2 in the message where I mentioned this](https://github.com/Sammyjo20/Saloon/issues/64#issuecomment-1170210141)).
It's easier for you to implement and maintain, and would give those of us with custom needs the opportunity to handle the resolving that fits our needs.

You could even implement the method by default, to resolve the Connector from the property.
And, for those of us needing separate resolving, we could just override it, and resolve it through service containers, or so.
This is also what I meant with that versatility, because using this approach, it could be implemented directly in Saloon itself, and be used for Laravel or anything else.
From what I can tell, though, we always need to define our Connector. So maybe define the resolve method as abstract, and we could get rid of the property.
This would also make it clearer for the developer that they need to define a Connector.
I could be forgetting something from the Manager, or so, though.

I also just realised that we can overwrite the existing [`getConnector()`](https://github.com/Sammyjo20/Saloon/blob/44fe2d29aba0148f96e5d874e9c6534b1e0c5ca6/src/Http/SaloonRequest.php#L120-L126).
All we'd have to do is resolve the instance, and call `setConnector()` first (for compatibility), and then return it.
The `bootConnector()` method is only referenced through the `getConnector()` method.
All it does is checking the type validity and setting the Connector in the property.
So that could be a short-term solution if anyone needs it right away.

**Comment by Sammyjo20** [comment]
Hey @rrolla I've implemented a new `resolveConnector` method which can be really easily overwritten in case you want to use dependency injection. Do you guys think this is a suitable and effective solution?
